#!/bin/sh -e
cat << EOF
menuentry 'Ubuntu for GVT (kernel 4.3.0)' --class ubuntu --class gnu-linux --class gnu --class os \$menuentry_id_option 'gnulinux-simple-${GRUB_DEVICE_UUID}' {
        recordfail
        load_video
        gfxmode \$linux_gfx_mode
        insmod gzio
        insmod part_msdos
        insmod ext2
        if [ x\$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root ${GRUB_DEVICE_UUID}
        else
          search --no-floppy --fs-uuid --set=root ${GRUB_DEVICE_UUID}
        fi
        linux   /boot/vmlinuz-4.3.0 root=/dev/xvda1 ro  quiet splash \$vt_handoff
        initrd /boot/initrd.img
}
