#!/bin/sh -e
cat << EOF
menuentry 'Ubuntu with Xen hypervisor XenGT(kernel KERNVER)' --class ubuntu --class gnu-linux --class gnu --class os --class xen \$menuentry_id_option 'xen-gnulinux-simple-${GRUB_DEVICE_UUID}' {
        insmod part_msdos
        insmod ext2
        set root='hd1,msdos1'
        if [ x\$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd1,msdos1 --hint-efi=hd1,msdos1 --hint-baremetal=ahci1,msdos1  ${GRUB_DEVICE_UUID}
        else
          search --no-floppy --fs-uuid --set=root ${GRUB_DEVICE_UUID}
        fi
        echo    'Loading Xen vgt ...'
        multiboot       /boot/xen-vgt.gz placeholder \${xen_rm_opts} 
        module  /boot/vmlinuz-KERNVER root=UUID=${GRUB_DEVICE_UUID} rw rd_NO_LUKS rd_NO_LVM LANG=en_US.UTF-8 rd_NO_MD SYSFONT=latarcyrheb-sun16 rhgb crashkernel=auto KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM ignore_loglevel console=tty0 console=hvc0 consoleblank=0 log_buf_len=4M i915.hvm_boot_foreground=1 i915.enable_cmd_parser=0
        echo 'Loading inital ramdisk ....'
        module /boot/initrd.img-KERNVER
}

