#!/bin/bash
sudo apt-get install git bin86 bcc python-dev iasl uuid-dev libperl-dev libgtk2.0-dev libaio-dev libyajl-dev bison libc6-dev-i386 texinfo libsdl2-dev libssl-dev mesa-common-dev libepoxy-dev libdrm-dev libgbm-dev libx11-dev autoconf libncurses5-dev libglib2.0-dev libpixman-1-dev libsdl-dev

sudo chmod 777 /etc/initramfs-tools/modules
echo "xengt" >> /etc/initramfs-tools/modules
echo "kvm" >> /etc/initramfs-tools/modules
sudo chmod 644 /etc/initramfs-tools/modules

git clone https://github.com/01org/igvtg-kernel kernel_src
cd kernel_src/
git checkout 2016q2-4.3.0
cp config-4.3.0-host .config
make -j8 && sudo make modules_install
sudo mkinitramfs -o /boot/initrd.img -v 4.3.0-rc6-vgt+
sudo cp arch/x86/boot/bzImage /boot/vmlinuz-4.3.0
sudo cp vgt.rules /etc/udev/rules.d
chmod a+x vgt_mgr
sudo cp vgt_mgr /usr/bin

cd ..

#need grub configure





