#!/bin/bash -e
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install git -y
sudo apt-get install bin86 -y
sudo apt-get install bcc -y
sudo apt-get install python-dev -y
sudo apt-get install iasl -y
sudo apt-get install uuid-dev -y
sudo apt-get install libperl-dev -y
sudo apt-get install libgtk2.0-dev -y
sudo apt-get install libaio-dev -y
sudo apt-get install libyajl-dev -y
sudo apt-get install bison -y
sudo apt-get install libc6-dev-i386 -y
sudo apt-get install texinfo -y
sudo apt-get install libsdl2-dev -y
sudo apt-get install libssl-dev -y
sudo apt-get install mesa-common-dev -y
sudo apt-get install libepoxy-dev -y
sudo apt-get install libdrm-dev -y
sudo apt-get install libgbm-dev -y
sudo apt-get install libx11-dev -y
sudo apt-get install autoconf -y
sudo apt-get install libncurses5-dev -y
sudo apt-get install libglib2.0-dev -y
sudo apt-get install libpixman-1-dev -y
sudo apt-get install libsdl-dev -y

if [ "$(cat /etc/initramfs-tools/modules | grep -o  xengt)" == "" ]
then
   sudo chmod 777 /etc/initramfs-tools/modules
   echo "xengt" >> /etc/initramfs-tools/modules
   echo "kvm" >> /etc/initramfs-tools/modules
   sudo chmod 644 /etc/initramfs-tools/modules
else
   echo "-----modules already added to /modules"
fi

cd ~/
if ! [ -a ~/kernel_src ]
then
   git clone https://github.com/emitchgustafson/igvtg-kernel kernel_src
   cd kernel_src/
   git checkout 2016q2-4.4.0
   cp config-4.3.0-host .config
   make -j8 && sudo make modules_install
   sudo mkinitramfs -o /boot/initrd.img-4.4.0 -v 4.4.0-vgt+
   sudo cp arch/x86/boot/bzImage /boot/vmlinuz-4.4.0
   sudo cp vgt.rules /etc/udev/rules.d
   chmod a+x vgt_mgr
   sudo cp vgt_mgr /usr/bin
else
   echo "-----kernel already exsists"
fi

sudo update-grub





