#!/bin/bash -e
sudo apt-get install git bin86 bcc python-dev iasl uuid-dev libperl-dev libgtk2.0-dev libaio-dev libyajl-dev bison libc6-dev-i386 texinfo libsdl2-dev libssl-dev mesa-common-dev libepoxy-dev libdrm-dev libgbm-dev libx11-dev autoconf libncurses5-dev libglib2.0-dev libpixman-1-dev libsdl-dev -y



if [ "$(cat /etc/initramfs-tools/modules | grep -o  xengt)" == "" ]
then
   sudo chmod 777 /etc/initramfs-tools/modules
   echo "xengt" >> /etc/initramfs-tools/modules
   echo "kvm" >> /etc/initramfs-tools/modules
   sudo chmod 644 /etc/initramfs-tools/modules
else
   echo "-----modules already added to /modules"
fi

if ! [ -a ~/kernel_src ]
then
   sudo cp 19_xengt /etc/grub.d/19_xengt
   sudo chmod 755 /etc/grub.d/19_xengt
   sudo chgrp root /etc/grub.d/19_xengt
   sudo chown root /etc/grub.d/19_xengt
else
   echo "-----grub.d already updated"
fi

cd ~/
if ! [ -a ~/kernel_src ]
then
   git clone https://github.com/01org/igvtg-kernel kernel_src
   cd kernel_src/
   git checkout 2016q2-4.3.0
   cp config-4.3.0-host .config
   make -j8 && sudo make modules_install
   sudo mkinitramfs -o /boot/initrd.img -v 4.3.0-rc6-vgt+
   sudo cp arch/x86/boot/bzImage /boot/vmlinuz-4.3.0
   sudo cp vgt.rules /etc/udev/rules.d
   chmod a+x vgt_mgr
   sudo cp vgt_mgr /usr/bin

else
   echo "-----kernel already exsists"
fi

cd ~/

if ! [ -a ~/xen_src ]
then
   git clone https://github.com/01org/igvtg-xen xen_src
   cd xen_src/
   git checkout 2016q2-4.6
   git clone https://github.com/01org/igvtg-qemu.git -b 2016q2-2.3.0 qemu-xen
   cp -r qemu-xen/ tools/
   sed -i '/QEMU_UPSTREAM_URL/s:http\://xenbits.xen.org/git-http/qemu-upstream-4.6-testing.git:$(XEN_ROOT)/tools/qemu-xen:' Config.mk
   sed -i '/QEMU_UPSTREAM_URL/s:git\://xenbits.xen.org/qemu-upstream-4.6-testing.git:$(XEN_ROOT)/tools/qemu-xen:' Config.mk
   ./autogen.sh
   ./configure --prefix=/usr  # XEN4.6 default path is /usr/local
   make -j8 xen tools
   sudo cp xen/xen.gz /boot/xen-vgt.gz
   sudo make install-tools PYTHON_PREFIX_ARG=
else
   echo "-----xen(igvt) already exsists"
fi

if ! [ -a /etc/init.d/startXen ]
then
   #Determine which network interface to use
   ETHER=$(ip addr | grep 2: | grep -o "e.*:" | cut -d ":" -f 1 -)

   #Install bridge utils
   sudo  apt-get install bridge-utils -y

   #setup script to run on boot to start xencommons
   echo "#!/bin/bash" > startXen
   echo "sudo etc/init.d/xencommons start" >> startXen
   echo "sudo brctl addbr xenbr0" >> startXen
   echo "sudo brctl addif xenbr0 $ETHER" >> startXen
   echo "sudo ifconfig $ETHER" >> startXen
   echo "sudo dhclient xenbr0" >> startXen

   sudo chmod ugo+x startXen
   sudo mv startXen /etc/init.d/startXen
   sudo update-rc.d startXen defaults
else
   echo "-----xen start-up script already created"
fi


sudo update-grub




